/-
  Auto-generated by chisel2sparkle.py
  Chisel → Sparkle Signal DSL 変換

  変換対応表:
    RegInit(x)          → Signal.register x input
    Signal.register init sig   → Signal.register init sig
    when(c) { a := b }   → Signal.mux c b <else>
    Module(new Sub)      → sub args
    io.out := expr       → pure functional return
    .foldl (fun acc x => (· + ·) <$> acc <*> x) (Signal.pure 0)       → .foldl (fun a b => (+) <$> a <*> b) zero
-/

import Sparkle
import Sparkle.Core.Signal
import Sparkle.Core.Domain

open Sparkle.Core.Signal
open Sparkle.Core.Domain

-- ============================================================
-- パラメータ定義 (自動変換: object → namespace/def)
-- ============================================================

namespace DATA
def W : Nat := 8
end DATA

namespace MAT
def N : Nat := 4
def ACC_W : Nat := DATA.W * 2 + log2Ceil(MAT.N + 1)
end MAT


-- ============================================================
-- PE_linear (自動変換: class → def)
-- ============================================================

structure PE_linearOutput where
  xOut : BitVec 8
  psumOut : BitVec DATA.W
deriving Inhabited

/-- PE_linear: Chisel Module からの自動変換 -/
def peLinear {dom : DomainConfig}
  (weightLoad : Signal dom Bool)
  (weightIn : Signal dom (BitVec 8))
  (xIn : Signal dom (BitVec 8))
  (psumIn : Signal dom (BitVec DATA.W))
  : Signal dom PE_linearOutput :=

  -- レジスタ (自動変換: RegInit → Signal.register / Signal.loop)
  let weightReg := Signal.loop fun prev =>
    let next := Signal.mux weightLoad weightIn prev
    Signal.register (0 : BitVec 8 : BitVec 8) next
  let xReg := Signal.register (0 : BitVec 8 : BitVec 8) xIn
  let psumReg := Signal.register (0 : BitVec MAT.ACC_W : BitVec DATA.W) psumIn + (xIn * weightReg)
  
  -- 組合せ論理 (自動変換: io.x := expr → let x := expr)
  let xOut := xReg
  let psumOut := psumReg
  
  -- 出力の組み立て
  (fun xOut psumOut => { xOut := xOut, psumOut := psumOut : PE_linearOutput })
    <$> xReg
    <*> psumReg


-- ============================================================
-- SystolicArrayLinear (自動変換: class → def)
-- ============================================================

/-- SystolicArrayLinear: Chisel Module からの自動変換 -/
def systolicArrayLinear {dom : DomainConfig} (Int : Nat := MAT.N)
  (weightLoad : Signal dom Bool)
  (weights : List (Signal dom (BitVec 8)))
  (xIn : List (Signal dom (BitVec 8)))
  : Signal dom List (BitVec DATA.W) :=

  -- サブモジュール (自動変換: Module(new Sub) → sub args)
  -- pe: Chisel Module(new PE_linear) → peLinear ...
  -- /* MANUAL */ 2D 配列 Seq.fill(N,N) → foldl の入れ子で接続
  
  -- 組合せ論理 (自動変換: io.x := expr → let x := expr)
  let pe(r)(c).io.weightLoad := weightLoad
  let pe(r)(c).io.weightIn := weights(r * N + c)
  let pe(r)(c).io.xIn := xIn(r)
  let pe(r)(c).io.xIn := pe(r)(c - 1).xOut
  let pe(r)(c).io.psumIn := (0 : BitVec _)
  let pe(r)(c).io.psumIn := pe(r - 1)(c).psumOut
  let psumOut(c) := pe(N - 1)(c).psumOut
  
  -- /* MANUAL */ 出力 io.psum_out の接続を確認してください
  Signal.pure (0 : List (BitVec DATA.W))


-- ============================================================
-- InputSkewBuffer (自動変換: class → def)
-- ============================================================

/-- InputSkewBuffer: Chisel Module からの自動変換 -/
def inputSkewBuffer {dom : DomainConfig} (Int : Nat := MAT.N)
  (in : List (Signal dom (BitVec 8)))
  : Signal dom List (BitVec 8) :=

  -- 組合せ論理 (自動変換: io.x := expr → let x := expr)
  let out(r) := signal
  
  -- /* MANUAL */ 出力 io.out の接続を確認してください
  Signal.pure (0 : List (BitVec 8))


-- ============================================================
-- OutputDeskewBuffer (自動変換: class → def)
-- ============================================================

/-- OutputDeskewBuffer: Chisel Module からの自動変換 -/
def outputDeskewBuffer {dom : DomainConfig} (Int : Nat := MAT.N)
  (in : List (Signal dom (BitVec DATA.W)))
  : Signal dom List (BitVec DATA.W) :=

  -- 組合せ論理 (自動変換: io.x := expr → let x := expr)
  let out(c) := signal
  
  -- /* MANUAL */ 出力 io.out の接続を確認してください
  Signal.pure (0 : List (BitVec DATA.W))


-- ============================================================
-- MatrixInputBuffer (自動変換: class → def)
-- ============================================================

structure MatrixInputBufferOutput where
  rowsOut : List (BitVec 8)
  feeding : Bool
  done : Bool
deriving Inhabited

/-- MatrixInputBuffer: Chisel Module からの自動変換 -/
def matrixInputBuffer {dom : DomainConfig} (Int : Nat := MAT.N)
  (elemIn : Signal dom (BitVec 8))
  (validIn : Signal dom Bool)
  : Signal dom MatrixInputBufferOutput :=

  -- レジスタ (自動変換: RegInit → Signal.register / Signal.loop)
  let state := Signal.loop fun prev =>
    let next := Signal.mux validIn sFeed prev
    Signal.register (sLoad : BitVec DATA.W) next
  let buf := Signal.register (VecInit(Seq.fill(N : BitVec DATA.W) (Signal.pure (VecInit(Seq.fill(N : BitVec DATA.W))
  let loadRow := Signal.loop fun prev =>
    let next := Signal.mux validIn 0 prev
    Signal.register (0 : BitVec DATA.W) next
  let loadCol := Signal.register (0 : BitVec DATA.W) (· + ·) <$> loadCol <*> 1
  let feedCol := Signal.register (0 : BitVec DATA.W) (· + ·) <$> feedCol <*> 1
  
  -- 組合せ論理 (自動変換: io.x := expr → let x := expr)
  let feeding := (state === sFeed)
  let done := false
  let rowsOut(r) := (0 : BitVec _)
  let buf(loadRow)(loadCol) := elemIn
  let rowsOut(r) := buf(r)(feedCol)
  let done := true
  
  -- 出力の組み立て
  (fun rowsOut feeding done => { rowsOut := rowsOut, feeding := feeding, done := done : MatrixInputBufferOutput })
    <$> Signal.pure (0 : List (BitVec 8))
    <*> (state === sFeed)
    <*> false


-- ============================================================
-- SDIP_linear (自動変換: class → def)
-- ============================================================

structure SDIP_linearOutput where
  out : BitVec DATA.W
  validOut : Bool
  ready : Bool
  colOut : BitVec DATA.W
  rowOut : BitVec DATA.W
deriving Inhabited

/-- SDIP_linear: Chisel Module からの自動変換 -/
def sdipLinear {dom : DomainConfig}
  (a : Signal dom (BitVec 8))
  (x : Signal dom (BitVec 8))
  (weightLoad : Signal dom Bool)
  (validIn : Signal dom Bool)
  : Signal dom SDIP_linearOutput :=

  -- レジスタ (自動変換: RegInit → Signal.register / Signal.loop)
  let weightRegs := Signal.register (VecInit(Seq.fill(N * N : BitVec DATA.W) (Signal.pure (VecInit(Seq.fill(N * N : BitVec DATA.W))
  let wCnt := Signal.loop fun prev =>
    let next := Signal.mux weightLoad 0 prev
    Signal.register (0 : BitVec DATA.W) next
  let wLoaded := Signal.loop fun prev =>
    let next := Signal.mux weightLoad true prev
    Signal.register (false : Bool) next
  let outCol := Signal.loop fun prev =>
    let next := Signal.mux pipeValid 0 prev
    Signal.register (0 : BitVec DATA.W) next
  let outRow := Signal.register (0 : BitVec DATA.W) (· + ·) <$> outRow <*> 1
  let validSr := Signal.register (0 : BitVec pipeline_depth : BitVec DATA.W) BitVec.append validSr(pipelineDepth - 2 0, feeding)
  
  -- 組合せ論理 (自動変換: io.x := expr → let x := expr)
  let weightRegs(wCnt) := a
  let xBuf.io.elemIn := x
  let xBuf.io.validIn := validIn && wLoaded
  let skew.io.in := x_buf.rowsOut
  let array.io.weightLoad := weightLoad
  let array.io.weights := weightRegs
  let array.io.dataIn := skew.out
  let deskew.io.in := array.psumOut
  let out := deskew.out(outCol)
  let colOut := outCol
  let rowOut := outRow
  let validOut := pipeValid
  let ready := wLoaded
  
  -- 出力の組み立て
  (fun out validOut ready colOut rowOut => { out := out, validOut := validOut, ready := ready, colOut := colOut, rowOut := rowOut : SDIP_linearOutput })
    <$> deskew.out(outCol)
    <*> pipeValid
    <*> wLoaded
    <*> outCol
    <*> outRow


-- ============================================================
-- 変換レポート
-- ============================================================
/-!
## 手動確認が必要な箇所

1. pe: 2D サブモジュール配列は foldl の入れ子で手動変換してください
2. SystolicArrayLinear: 出力 psum_out の式が検出できませんでした
3. InputSkewBuffer: 出力 out の式が検出できませんでした
4. OutputDeskewBuffer: 出力 out の式が検出できませんでした
5. MatrixInputBuffer.buf: レジスタの更新元が検出できませんでした
6. SDIP_linear.weight_regs: レジスタの更新元が検出できませんでした
-/