/-
  H.264 SPS/PPS Pre-computed Header Data

  Pre-computed SPS and PPS NAL units for a minimal H.264 Baseline configuration:
  - 16x16 resolution (1 macroblock)
  - Profile: 66 (Baseline), Level: 1.0
  - CAVLC entropy coding, QP: 26 (pic_init_qp_minus26 = 0)
  - Generated by openh264 and validated with ffprobe

  These are fixed byte arrays that the host prepends to the .h264 output.

  Reference: ITU-T H.264 Section 7.3.2.1 (SPS), 7.3.2.2 (PPS)
-/

import Sparkle

set_option maxRecDepth 8192
set_option maxHeartbeats 800000

namespace Sparkle.IP.Video.H264.SPSPPSData

-- ============================================================================
-- SPS (Sequence Parameter Set) NAL unit
-- ============================================================================

/-- Pre-computed SPS NAL unit for 16x16 Baseline Profile.
    Generated by openh264 encoder, validated with ffprobe.

    SPS RBSP content (parsed):
      profile_idc = 66 (0x42, Baseline)
      constraint_set0_flag = 1, constraint_set1_flag = 1, others = 0 -> 0xC0
      level_idc = 10 (0x0A)
      seq_parameter_set_id = 0
      log2_max_frame_num_minus4 = 11 -> frame_num is 15 bits
      pic_order_cnt_type = 2 (no POC in slice header)
      max_num_ref_frames = 1
      gaps_in_frame_num_value_allowed_flag = 0
      pic_width_in_mbs_minus1 = 0 -> 16 pixels
      pic_height_in_map_units_minus1 = 0 -> 16 pixels
      frame_mbs_only_flag = 1
      direct_8x8_inference_flag = 0
      frame_cropping_flag = 0
      vui_parameters_present_flag = 1 (minimal VUI)
-/
def spsNALUnit : Array (BitVec 8) :=
  #[ 0x00#8, 0x00#8, 0x00#8, 0x01#8,   -- 4-byte start code
     0x67#8,                              -- NAL header: ref_idc=3, type=7 (SPS)
     0x42#8, 0xC0#8, 0x0A#8,             -- profile=66, constraints=0xC0, level=10
     0x8C#8, 0x69#8, 0xC8#8,             -- SPS RBSP body
     0x07#8, 0x84#8, 0x42#8, 0x35#8      -- continued + VUI + trailing
  ]

-- ============================================================================
-- PPS (Picture Parameter Set) NAL unit
-- ============================================================================

/-- Pre-computed PPS NAL unit.
    Generated by openh264 encoder, validated with ffprobe.

    PPS RBSP content (parsed):
      pic_parameter_set_id = 0
      seq_parameter_set_id = 0
      entropy_coding_mode_flag = 0 (CAVLC)
      bottom_field_pic_order_in_frame_present_flag = 0
      num_slice_groups_minus1 = 0
      num_ref_idx_l0_default_active_minus1 = 0
      num_ref_idx_l1_default_active_minus1 = 0
      weighted_pred_flag = 0
      weighted_bipred_idc = 0
      pic_init_qp_minus26 = 0
      pic_init_qs_minus26 = 0
      chroma_qp_index_offset = 0
      deblocking_filter_control_present_flag = 1
      constrained_intra_pred_flag = 0
      redundant_pic_cnt_present_flag = 0
-/
def ppsNALUnit : Array (BitVec 8) :=
  #[ 0x00#8, 0x00#8, 0x00#8, 0x01#8,   -- 4-byte start code
     0x68#8,                              -- NAL header: ref_idc=3, type=8 (PPS)
     0xCE#8, 0x3C#8, 0x80#8              -- PPS RBSP + trailing
  ]

-- ============================================================================
-- Slice header for IDR frame
-- ============================================================================

/-- Pre-computed slice header bits for an IDR I-frame.
    Must match the SPS/PPS parameters above.

    Slice header content:
      first_mb_in_slice = 0 (ue: 1, 1 bit)
      slice_type = 2 (I-slice, ue: 011, 3 bits)
      pic_parameter_set_id = 0 (ue: 1, 1 bit)
      frame_num = 0 (15 bits, since log2_max_frame_num_minus4=11)
      idr_pic_id = 0 (ue: 1, 1 bit)
      (no POC since pic_order_cnt_type=2)
      no_output_of_prior_pics_flag = 0 (1 bit)
      long_term_reference_flag = 0 (1 bit)
      slice_qp_delta = 0 (se: 1, 1 bit)
      disable_deblocking_filter_idc = 1 (ue: 010, 3 bits)

    Total: 1+3+1+15+1+1+1+1+3 = 27 bits
    Packed: 1 011 1 000000000000000 1 0 0 1 010 [00000]
          = 10111 00000000 00000001 001010 00
          = 0xB8 0x00 0x09 0x40
    (last byte has 5 padding bits)
-/
def sliceHeaderBits : Array (BitVec 8) :=
  #[ 0xB8#8, 0x00#8, 0x09#8, 0x40#8 ]

/-- Slice header bit length (number of valid bits in sliceHeaderBits) -/
def sliceHeaderBitLen : Nat := 27

-- ============================================================================
-- IDR Slice NAL unit start code + header
-- ============================================================================

/-- Start code + NAL header for an IDR slice.
    NAL header: forbidden=0, ref_idc=3, type=5 (IDR) -> 0x65 -/
def idrSliceNALHeader : Array (BitVec 8) :=
  #[ 0x00#8, 0x00#8, 0x00#8, 0x01#8,   -- 4-byte start code
     0x65#8 ]                             -- NAL header: ref_idc=3, type=5 (IDR)

-- ============================================================================
-- Macroblock header for Intra_4x4
-- ============================================================================

/-- Macroblock header for I_4x4 macroblock type (mb_type = 0), 4:2:0.

    Order per H.264 spec 7.3.5 (macroblock_layer + mb_pred):
    1. mb_type = 0 (ue: 1, 1 bit)
    2. For I_4x4, 16x prev_intra4x4_pred_mode_flag = 1 (16 bits)
    3. intra_chroma_pred_mode = 0 (DC) (ue: 1, 1 bit)   [in mb_pred, before CBP]
    4. coded_block_pattern: CBP=15 -> codeNum=2 -> ue(2) = 011 (3 bits)
    5. mb_qp_delta = 0 (se: 1, 1 bit)

    Total: 1 + 16 + 1 + 3 + 1 = 22 bits
    Packed: 1 1111111111111111 1 011 1 [00]
          = 11111111 11111111 110111[00]
          = 0xFF 0xFF 0xDC
    (last byte has 2 padding bits)
-/
def mbHeaderBits : Array (BitVec 8) :=
  #[ 0xFF#8, 0xFF#8, 0xDC#8 ]

/-- Macroblock header bit length -/
def mbHeaderBitLen : Nat := 22

-- ============================================================================
-- Verification
-- ============================================================================

#eval do
  IO.println s!"SPS NAL unit: {spsNALUnit.size} bytes"
  IO.println s!"PPS NAL unit: {ppsNALUnit.size} bytes"
  IO.println s!"Slice header: {sliceHeaderBits.size} bytes ({sliceHeaderBitLen} bits)"
  IO.println s!"IDR NAL header: {idrSliceNALHeader.size} bytes"
  IO.println s!"MB header: {mbHeaderBits.size} bytes ({mbHeaderBitLen} bits)"

end Sparkle.IP.Video.H264.SPSPPSData
